FROM mcr.microsoft.com/dotnet/sdk:3.1
RUN dotnet tool install -g dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"
COPY . /app
WORKDIR /app
RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]
EXPOSE 80
RUN chmod +x ./entrypoint.sh
CMD /bin/bash ./entrypoint.sh
