### Stage 1: Build ###
## our custom image for with git already installed and only for building single page aaplication(spa)
FROM brahimafa/front-spa as build
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build --prod


### Stage 2: Run ###

FROM nginx:1.17.1-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
